const countryMap = {
  Afghanistan: "AF",
  Albania: "AL",
  Algeria: "DZ",
  "American Samoa": "AS",
  Andorra: "AD",
  Angola: "AO",
  Anguilla: "AI",
  Antarctica: "AQ",
  "Antigua and Barbuda": "AG",
  Argentina: "AR",
  Armenia: "AM",
  Aruba: "AW",
  Australia: "AU",
  Austria: "AT",
  Azerbaijan: "AZ",
  Bahamas: "BS",
  Bahrain: "BH",
  Bangladesh: "BD",
  Barbados: "BB",
  Belarus: "BY",
  Belgium: "BE",
  Belize: "BZ",
  Benin: "BJ",
  Bermuda: "BM",
  Bhutan: "BT",
  Bolivia: "BO",
  "Bosnia and Herzegovina": "BA",
  Botswana: "BW",
  "Bouvet Island": "BV",
  Brazil: "BR",
  "British Indian Ocean Territory": "IO",
  "Brunei Darussalam": "BN",
  Bulgaria: "BG",
  "Burkina Faso": "BF",
  Burundi: "BI",
  Cambodia: "KH",
  Cameroon: "CM",
  Canada: "CA",
  "Cape Verde": "CV",
  "Cayman Islands": "KY",
  "Central African Republic": "CF",
  Chad: "TD",
  Chile: "CL",
  "People's Republic of China": "CN",
  China: "CN",
  "Christmas Island": "CX",
  "Cocos (Keeling) Islands": "CC",
  Colombia: "CO",
  Comoros: "KM",
  "Republic of the Congo": "CG",
  Congo: "CD",
  "Democratic Republic of the Congo": "CD",
  "Cook Islands": "CK",
  "Costa Rica": "CR",
  "Cote d'Ivoire": "CI",
  "Côte d'Ivoire": "CI",
  "Ivory Coast": "CI",
  Croatia: "HR",
  Cuba: "CU",
  Cyprus: "CY",
  "Czech Republic": "CZ",
  Czechia: "CZ",
  Denmark: "DK",
  Djibouti: "DJ",
  Dominica: "DM",
  "Dominican Republic": "DO",
  Ecuador: "EC",
  Egypt: "EG",
  "El Salvador": "SV",
  "Equatorial Guinea": "GQ",
  Eritrea: "ER",
  Estonia: "EE",
  Ethiopia: "ET",
  "Falkland Islands (Malvinas)": "FK",
  "Faroe Islands": "FO",
  Fiji: "FJ",
  Finland: "FI",
  France: "FR",
  "French Guiana": "GF",
  "French Polynesia": "PF",
  "French Southern Territories": "TF",
  Gabon: "GA",
  "Republic of The Gambia": "GM",
  "The Gambia": "GM",
  Gambia: "GM",
  Georgia: "GE",
  Germany: "DE",
  Ghana: "GH",
  Gibraltar: "GI",
  Greece: "GR",
  Greenland: "GL",
  Grenada: "GD",
  Guadeloupe: "GP",
  Guam: "GU",
  Guatemala: "GT",
  Guinea: "GN",
  "Guinea-Bissau": "GW",
  Guyana: "GY",
  Haiti: "HT",
  "Heard Island and McDonald Islands": "HM",
  "Holy See (Vatican City State)": "VA",
  Honduras: "HN",
  "Hong Kong": "HK",
  Hungary: "HU",
  Iceland: "IS",
  India: "IN",
  Indonesia: "ID",
  "Islamic Republic of Iran": "IR",
  Iran: "IR",
  Iraq: "IQ",
  Ireland: "IE",
  Israel: "IL",
  Italy: "IT",
  Jamaica: "JM",
  Japan: "JP",
  Jordan: "JO",
  Kazakhstan: "KZ",
  Kenya: "KE",
  Kiribati: "KI",
  "North Korea": "KP",
  "South Korea": "KR",
  "Korea, Republic of": "KR",
  "Republic of Korea": "KR",
  Kuwait: "KW",
  Kyrgyzstan: "KG",
  "Lao People's Democratic Republic": "LA",
  Latvia: "LV",
  Lebanon: "LB",
  Lesotho: "LS",
  Liberia: "LR",
  Libya: "LY",
  Liechtenstein: "LI",
  Lithuania: "LT",
  Luxembourg: "LU",
  Macao: "MO",
  Madagascar: "MG",
  Malawi: "MW",
  Malaysia: "MY",
  Maldives: "MV",
  Mali: "ML",
  Malta: "MT",
  "Marshall Islands": "MH",
  Martinique: "MQ",
  Mauritania: "MR",
  Mauritius: "MU",
  Mayotte: "YT",
  Mexico: "MX",
  "Micronesia, Federated States of": "FM",
  "Moldova, Republic of": "MD",
  Monaco: "MC",
  Mongolia: "MN",
  Montserrat: "MS",
  Morocco: "MA",
  Mozambique: "MZ",
  Myanmar: "MM",
  Namibia: "NA",
  Nauru: "NR",
  Nepal: "NP",
  Netherlands: "NL",
  "The Netherlands": "NL",
  "Netherlands (Kingdom of the)": "NL",
  "New Caledonia": "NC",
  "New Zealand": "NZ",
  Nicaragua: "NI",
  Niger: "NE",
  Nigeria: "NG",
  Niue: "NU",
  "Norfolk Island": "NF",
  "The Republic of North Macedonia": "MK",
  "North Macedonia": "MK",
  "Northern Mariana Islands": "MP",
  Norway: "NO",
  Oman: "OM",
  Pakistan: "PK",
  Palau: "PW",
  "State of Palestine": "PS",
  Palestine: "PS",
  Panama: "PA",
  "Papua New Guinea": "PG",
  Paraguay: "PY",
  Peru: "PE",
  Philippines: "PH",
  Pitcairn: "PN",
  "Pitcairn Islands": "PN",
  Poland: "PL",
  Portugal: "PT",
  "Puerto Rico": "PR",
  Qatar: "QA",
  Reunion: "RE",
  Romania: "RO",
  "Russian Federation": "RU",
  Russia: "RU",
  Rwanda: "RW",
  "Saint Helena": "SH",
  "Saint Kitts and Nevis": "KN",
  "Saint Lucia": "LC",
  "Saint Pierre and Miquelon": "PM",
  "Saint Vincent and the Grenadines": "VC",
  Samoa: "WS",
  "San Marino": "SM",
  "Sao Tome and Principe": "ST",
  "Saudi Arabia": "SA",
  Senegal: "SN",
  Seychelles: "SC",
  "Sierra Leone": "SL",
  Singapore: "SG",
  Slovakia: "SK",
  Slovenia: "SI",
  "Solomon Islands": "SB",
  Somalia: "SO",
  "South Africa": "ZA",
  "South Georgia and the South Sandwich Islands": "GS",
  Spain: "ES",
  "Sri Lanka": "LK",
  Sudan: "SD",
  Suriname: "SR",
  "Svalbard and Jan Mayen": "SJ",
  Eswatini: "SZ",
  Sweden: "SE",
  Switzerland: "CH",
  "Syrian Arab Republic": "SY",
  "Taiwan, Province of China": "TW",
  Taiwan: "TW",
  Tajikistan: "TJ",
  "United Republic of Tanzania": "TZ",
  Tanzania: "TZ",
  Thailand: "TH",
  "Timor-Leste": "TL",
  Togo: "TG",
  Tokelau: "TK",
  Tonga: "TO",
  "Trinidad and Tobago": "TT",
  Tunisia: "TN",
  Türkiye: "TR",
  Turkey: "TR",
  Turkmenistan: "TM",
  "Turks and Caicos Islands": "TC",
  Tuvalu: "TV",
  Uganda: "UG",
  Ukraine: "UA",
  "United Arab Emirates": "AE",
  UAE: "AE",
  "United Kingdom": "GB",
  UK: "GB",
  "Great Britain": "GB",
  "United States of America": "US",
  "United States": "US",
  USA: "US",
  "U.S.A.": "US",
  US: "US",
  "U.S.": "US",
  "United States Minor Outlying Islands": "UM",
  Uruguay: "UY",
  Uzbekistan: "UZ",
  Vanuatu: "VU",
  Venezuela: "VE",
  Vietnam: "VN",
  "Virgin Islands, British": "VG",
  "Virgin Islands, U.S.": "VI",
  "Wallis and Futuna": "WF",
  "Western Sahara": "EH",
  Yemen: "YE",
  Zambia: "ZM",
  Zimbabwe: "ZW",
  "Åland Islands": "AX",
  "Aland Islands": "AX",
  "Bonaire, Sint Eustatius and Saba": "BQ",
  Curaçao: "CW",
  Guernsey: "GG",
  "Isle of Man": "IM",
  Jersey: "JE",
  Montenegro: "ME",
  "Saint Barthélemy": "BL",
  "Saint Martin (French part)": "MF",
  Serbia: "RS",
  "Sint Maarten (Dutch part)": "SX",
  "South Sudan": "SS",
  Kosovo: "XK",
  iranian: "IR",
  albanian: "AL",
  "wallis and futuna islander": "WF",
  belgian: "BE",
  indian: "IN",
  "saint-pierrais, miquelonnais": "PM",
  "saint vincentian": "VC",
  marshallese: "MH",
  turkmen: "TM",
  nigerian: "NG",
  tunisian: "TN",
  seychellois: "SC",
  uruguayan: "UY",
  "french polynesian": "PF",
  emirati: "AE",
  "heard and mcdonald islander": "HM",
  haitian: "HT",
  turkish: "TR",
  guyanese: "GY",
  jordanian: "JO",
  slovene: "SI",
  omani: "OM",
  "south african": "ZA",
  portuguese: "PT",
  ugandan: "UG",
  danish: "DK",
  dominican: "DM",
  tongan: "TO",
  "norfolk islander": "NF",
  maltese: "MT",
  bangladeshi: "BD",
  salvadoran: "SV",
  thai: "TH",
  zimbabwean: "ZW",
  kazakhstani: "KZ",
  malaysian: "MY",
  moldovan: "MD",
  ålandish: "AX",
  "hong konger": "HK",
  manx: "IM",
  mosotho: "LS",
  "ni-vanuatu": "VU",
  guatemalan: "GT",
  senegalese: "SN",
  german: "DE",
  antarctican: "AQ",
  montserratian: "MS",
  "pitcairn islander": "PN",
  "south sudanese": "SS",
  "guinea-bissauan": "GW",
  cypriot: "CY",
  algerian: "DZ",
  palestinian: "PS",
  georgian: "GE",
  kuwaiti: "KW",
  mauritian: "MU",
  kosovar: "XK",
  "virgin islander": "VG",
  cameroonian: "CM",
  british: "GB",
  trinidadian: "TT",
  burkinabe: "BF",
  serbian: "RS",
  togolese: "TG",
  "christmas islander": "CX",
  sahrawi: "EH",
  irish: "IE",
  belarusian: "BY",
  filipino: "PH",
  "cocos islander": "CC",
  colombian: "CO",
  namibian: "NA",
  ivorian: "CI",
  american: "MP",
  romanian: "RO",
  greek: "GR",
  dutch: "BQ",
  guadeloupian: "GP",
  "turks and caicos islander": "TC",
  russian: "RU",
  cambodian: "KH",
  greenlandic: "GL",
  barbadian: "BB",
  "saint lucian": "LC",
  mozambican: "MZ",
  "north korean": "KP",
  armenian: "AM",
  gabonese: "GA",
  norwegian: "NO",
  faroese: "FO",
  yemeni: "YE",
  nigerien: "NE",
  italian: "IT",
  "puerto rican": "PR",
  chinese: "CN",
  paraguayan: "PY",
  "new caledonian": "NC",
  french: "FR",
  egyptian: "EG",
  "sierra leonean": "SL",
  brazilian: "BR",
  zambian: "ZM",
  eritrean: "ER",
  "saint martin islander": "MF",
  "falkland islander": "FK",
  réunionese: "RE",
  montenegrin: "ME",
  liberian: "LR",
  syrian: "SY",
  tokelauan: "TK",
  bulgarian: "BG",
  malian: "ML",
  laotian: "LA",
  lithuanian: "LT",
  mauritanian: "MR",
  slovak: "SK",
  "cook islander": "CK",
  somali: "SO",
  fijian: "FJ",
  kenyan: "KE",
  "i-kiribati": "KI",
  "equatorial guinean": "GQ",
  libyan: "LY",
  luxembourger: "LU",
  panamanian: "PA",
  guinean: "GN",
  "cape verdian": "CV",
  indonesian: "ID",
  "kittitian or nevisian": "KN",
  "costa rican": "CR",
  "channel islander": "GG",
  spanish: "ES",
  malawian: "MW",
  sammarinese: "SM",
  bahraini: "BH",
  caymanian: "KY",
  "south korean": "KR",
  angolan: "AO",
  finnish: "FI",
  cuban: "CU",
  niuean: "NU",
  ghanaian: "GH",
  ecuadorean: "EC",
  guamanian: "GU",
  bahamian: "BS",
  micronesian: "FM",
  tuvaluan: "TV",
  swiss: "CH",
  chadian: "TD",
  hungarian: "HU",
  martinican: "MQ",
  macedonian: "MK",
  nicaraguan: "NI",
  mexican: "MX",
  chilean: "CL",
  bruneian: "BN",
  guianan: "GF",
  austrian: "AT",
  croatian: "HR",
  czech: "CZ",
  monegasque: "MC",
  palauan: "PW",
  swedish: "SE",
  burundian: "BI",
  congolese: "CG",
  liechtensteiner: "LI",
  "new zealander": "NZ",
  japanese: "JP",
  estonian: "EE",
  grenadian: "GD",
  "st. maartener": "SX",
  azerbaijani: "AZ",
  "solomon islander": "SB",
  nepalese: "NP",
  aruban: "AW",
  "american islander": "UM",
  gambian: "GM",
  tanzanian: "TZ",
  djibouti: "DJ",
  "sri lankan": "LK",
  peruvian: "PE",
  tadzhik: "TJ",
  "papua new guinean": "PG",
  bolivian: "BO",
  uzbekistani: "UZ",
  "saint barthélemy islander": "BL",
  jamaican: "JM",
  "east timorese": "TL",
  comoran: "KM",
  samoan: "WS",
  surinamer: "SR",
  maldivan: "MV",
  "sao tomean": "ST",
  mongolian: "MN",
  curaçaoan: "CW",
  sudanese: "SD",
  motswana: "BW",
  israeli: "IL",
  belizean: "BZ",
  beninese: "BJ",
  latvian: "LV",
  argentine: "AR",
  burmese: "MM",
  singaporean: "SG",
  anguillian: "AI",
  bermudian: "BM",
  rwandan: "RW",
  "saudi arabian": "SA",
  vietnamese: "VN",
  andorran: "AD",
  "south georgian south sandwich islander": "GS",
  honduran: "HN",
  vatican: "VA",
  australian: "AU",
  pakistani: "PK",
  afghan: "AF",
  icelander: "IS",
  malagasy: "MG",
  ethiopian: "ET",
  qatari: "QA",
  kirghiz: "KG",
  "central african": "CF",
  gibraltar: "GI",
  macanese: "MO",
  swazi: "SZ",
  mahoran: "YT",
  ukrainian: "UA",
  "saint helenian": "SH",
  lebanese: "LB",
  venezuelan: "VE",
  iraqi: "IQ",
  "american samoan": "AS",
  "antiguan, barbudan": "AG",
  polish: "PL",
  taiwanese: "TW",
  canadian: "CA",
  nauruan: "NR",
  bhutanese: "BT",
  moroccan: "MA",
  "bosnian, herzegovinian": "BA",
  american: "US",
  britain: "GB",
};

const sortedGeoTriggers = Object.keys(countryMap).sort(
  (a, b) => b.length - a.length,
);

const parseNLQ = (q) => {
  const query = q.toLowerCase();
  const filters = {
    country_ids: [],
    age_groups: [],
    genders: [],
  };

  // 1. Gender Tokens (supports "males and females")
  if (/\b(females?|women|woman|girls?|ladies|lady)\b/.test(query))
    filters.genders.push("female");
  if (/\b(males?|men|man|boys?|guys?|gentlemen|gentleman)\b/.test(query))
    filters.genders.push("male");

  // 2. Age Group Tokens (supports "teenagers and adults")
  if (/\b(children|child|kids?|infants?)\b/.test(query))
    filters.age_groups.push("child");
  if (/\b(teenagers?|teens?|adolescents?)\b/.test(query))
    filters.age_groups.push("teenager");
  if (/\b(adults?|grown-ups?)\b/.test(query)) filters.age_groups.push("adult");
  if (/\b(seniors?|elderly|retired|old people)\b/.test(query))
    filters.age_groups.push("senior");

  // 3. Special "Young" Rule (16-24)
  if (/\byoung\b|\byouth\b/.test(query)) {
    filters.min_age = 16;
    filters.max_age = 24;
  }

  // 4. Comparative Age Logic
  const aboveMatch = query.match(/(?:above|over|older than)\s+(\d+)/);
  if (aboveMatch) filters.min_age = parseInt(aboveMatch[1]) + 1;

  const belowMatch = query.match(/(?:below|under|younger than)\s+(\d+)/);
  if (belowMatch) filters.max_age = parseInt(belowMatch[1]) - 1;

  // 5. Country & Demonym Parsing (Supports multiple countries)
  // We check for full triggers first (longest matches)
  for (const trigger of sortedGeoTriggers) {
    const geoRegex = new RegExp(`\\b${trigger}\\b`, "i");
    if (geoRegex.test(query)) {
      const code = countryMap[trigger].toUpperCase();
      if (!filters.country_ids.includes(code)) {
        filters.country_ids.push(code);
      }
    }
  }

  // 6. Plural Fallback (only if no countries were found)
  if (filters.country_ids.length === 0) {
    const words = query.split(/\s+/);
    for (const word of words) {
      const singularCandidate = word.replace(/s$/, "").replace(/[^\w]/g, "");
      // Check if the singular version of a word exists in our map
      const match = Object.keys(countryMap).find(
        (k) => k.toLowerCase() === singularCandidate.toLowerCase(),
      );
      if (match) {
        filters.country_ids.push(countryMap[match].toUpperCase());
      }
    }
  }

  // Clean up: Remove empty arrays before returning
  const finalFilters = {};
  if (filters.country_ids.length > 0)
    finalFilters.country_ids = filters.country_ids;
  if (filters.age_groups.length > 0)
    finalFilters.age_group =
      filters.age_groups.length === 1
        ? filters.age_groups[0]
        : { $in: filters.age_groups };
  if (filters.genders.length > 0)
    finalFilters.gender =
      filters.genders.length === 1
        ? filters.genders[0]
        : { $in: filters.genders };

  // Carry over numeric ages
  if (filters.min_age) finalFilters.min_age = filters.min_age;
  if (filters.max_age) finalFilters.max_age = filters.max_age;

  return Object.keys(finalFilters).length > 0 ? finalFilters : null;
};

module.exports = parseNLQ;
